#!/bin/bash -u

# stop all docker instances and remove images
# maintainer - kelvin cui
# email - kelvinwhcui@gmail.com


docker stop $(docker ps -aq)
docker rm $(docker ps -aq)

IMAGE_NAME="default_utfr_ros2_image"

docker image rm $IMAGE_NAME

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

bash ${SCRIPT_DIR}/start_docker
